### ISSUE TITLE
Missing data on published Detection message

### ISSUE THREAD

**Issue by AndresGalaviz** [NVIDIA-AI-IOT/ros2-nvapriltags#9]
Hello,

I've managed to get this building and running in our application. It's pretty cool to see this running on the GPU :)

One thing I have noticed is that not all contents of the detection message are filled up. An echo of the detection shows this:

```
---
header:
  stamp:
    sec: 1618512737
    nanosec: 721473880
  frame_id: camera_front_color_optical_frame
detections:
- family: 36h11
  id: 28
  hamming: 0
  goodness: 0.0
  decision_margin: 0.0
  centre:
    x: 0.0
    y: 0.0
  corners:
  - x: 286.0
    y: 7.0
  - x: 359.0
    y: 13.0
  - x: 353.0
    y: 87.0
  - x: 282.0
    y: 82.0
  homography: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
```

Upon looking at the Node code it does seem that the assignment of the data is missing and so it defaults to 0
